use_frameworks!

platform :ios, '8.0'

target 'SHTDragView_Example' do
  pod 'SHTDragView', :path => '../'

  target 'SHTDragView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
